# Generated by Django 3.2.9 on 2021-11-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=40, verbose_name='Nombre')),
                ('direccion', models.TextField(max_length=60, verbose_name='Direccion')),
                ('ciudad', models.TextField(max_length=15, verbose_name='Ciudad')),
                ('poblacion', models.CharField(choices=[('R', 'rural'), ('U', 'urbano')], max_length=3)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CAS', 'Casa'), ('APT', 'Apartamento'), ('LOC', 'Local')], max_length=3)),
                ('area', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('estrato', models.IntegerField()),
                ('contrato', models.CharField(choices=[('ALQ', 'Alquiler'), ('VEN', 'Venta')], max_length=3)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('coordenadas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=15, unique=True, verbose_name='usuario')),
                ('nombre', models.TextField(max_length=30, verbose_name='nombre')),
                ('password', models.TextField(max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
