# Generated by Django 3.2.9 on 2021-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(db_index=True, max_length=200)),
                ('direccion', models.TextField(db_index=True, max_length=100)),
                ('ciudad', models.TextField(db_index=True, max_length=100)),
                ('poblacion', models.CharField(choices=[('R', 'rural'), ('U', 'urbano')], max_length=3)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tipo', models.CharField(choices=[('CAS', 'Casa'), ('APT', 'Apartamento'), ('LOC', 'Local')], max_length=3)),
                ('area', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('estrato', models.IntegerField()),
                ('contrato', models.CharField(choices=[('ALQ', 'Alquiler'), ('VEN', 'Venta')], max_length=3)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('coordenadas', models.CharField(max_length=100)),
            ],
        ),
    ]
