# Generated by Django 3.2.9 on 2021-11-19 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInmuebles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator])),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmueblesApp.inmuebles')),
            ],
        ),
    ]
