# Generated by Django 3.2.9 on 2021-11-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=40, verbose_name='Nombre')),
                ('direccion', models.TextField(max_length=60, verbose_name='Direccion')),
                ('ciudad', models.TextField(max_length=15, verbose_name='Ciudad')),
                ('poblacion', models.CharField(choices=[('R', 'rural'), ('U', 'urbano')], max_length=3)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CAS', 'Casa'), ('APT', 'Apartamento'), ('LOC', 'Local')], max_length=3)),
                ('area', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('estrato', models.IntegerField()),
                ('contrato', models.CharField(choices=[('ALQ', 'Alquiler'), ('VEN', 'Venta')], max_length=3)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('coordenadas', models.CharField(max_length=100)),
            ],
        ),
    ]
